### ISSUE TITLE
Include Luiz planning doc in this project

### ISSUE THREAD

**Issue by andrawaag** [ejp-rd-vp/ejprd-federated-analysis#16]
For Andra and Marco

**Comment by mroos** [comment]
Marco updated the description and Readme of this project to include the link to the original Google doc by Luiz Bonino. The link added is https://docs.google.com/document/d/1lCsLNSHPHNEOUvsoDy4cOgUCjSkvv2be7vLOL_Vp6wU/edit?usp=drive_link
